// Mocks generated by Mockito 5.4.4 from annotations
// in kawach/test/features/sos/sos_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:isar/isar.dart' as _i3;
import 'package:kawach/core/database/local_database.dart' as _i6;
import 'package:kawach/core/database/models/evidence_local.dart' as _i8;
import 'package:kawach/core/database/models/sos_alert_local.dart' as _i7;
import 'package:kawach/features/sos/data/sos_queue_manager.dart' as _i9;
import 'package:kawach/features/sos/data/sos_remote_datasource.dart' as _i4;
import 'package:kawach/features/sos/domain/entities/sos_alert.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSosAlert_0 extends _i1.SmartFake implements _i2.SosAlert {
  _FakeSosAlert_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsar_1 extends _i1.SmartFake implements _i3.Isar {
  _FakeIsar_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SosRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSosRemoteDataSource extends _i1.Mock
    implements _i4.SosRemoteDataSource {
  MockSosRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SosAlert> triggerSOS({
    required double? lat,
    required double? lng,
    required int? battery,
    required String? triggerType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #triggerSOS,
          [],
          {
            #lat: lat,
            #lng: lng,
            #battery: battery,
            #triggerType: triggerType,
          },
        ),
        returnValue: _i5.Future<_i2.SosAlert>.value(_FakeSosAlert_0(
          this,
          Invocation.method(
            #triggerSOS,
            [],
            {
              #lat: lat,
              #lng: lng,
              #battery: battery,
              #triggerType: triggerType,
            },
          ),
        )),
      ) as _i5.Future<_i2.SosAlert>);

  @override
  _i5.Future<void> cancelSOS(
    String? sosId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSOS,
          [
            sosId,
            reason,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i2.SosAlert?> listenToActiveSOS(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenToActiveSOS,
          [userId],
        ),
        returnValue: _i5.Stream<_i2.SosAlert?>.empty(),
      ) as _i5.Stream<_i2.SosAlert?>);
}

/// A class which mocks [LocalDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatabase extends _i1.Mock implements _i6.LocalDatabase {
  MockLocalDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Isar get isar => (super.noSuchMethod(
        Invocation.getter(#isar),
        returnValue: _FakeIsar_1(
          this,
          Invocation.getter(#isar),
        ),
      ) as _i3.Isar);

  @override
  set isar(_i3.Isar? _isar) => super.noSuchMethod(
        Invocation.setter(
          #isar,
          _isar,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveSosAlert(_i7.SosAlertLocal? alert) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSosAlert,
          [alert],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveEvidence(_i8.EvidenceLocal? evidence) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEvidence,
          [evidence],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.SosAlertLocal>> getUnsyncedAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedAlerts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i7.SosAlertLocal>>.value(<_i7.SosAlertLocal>[]),
      ) as _i5.Future<List<_i7.SosAlertLocal>>);

  @override
  _i5.Future<List<_i8.EvidenceLocal>> getUnuploadedEvidence() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnuploadedEvidence,
          [],
        ),
        returnValue:
            _i5.Future<List<_i8.EvidenceLocal>>.value(<_i8.EvidenceLocal>[]),
      ) as _i5.Future<List<_i8.EvidenceLocal>>);
}

/// A class which mocks [SosQueueManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSosQueueManager extends _i1.Mock implements _i9.SosQueueManager {
  MockSosQueueManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> enqueue({
    required double? lat,
    required double? lng,
    required int? battery,
    required String? triggerType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [],
          {
            #lat: lat,
            #lng: lng,
            #battery: battery,
            #triggerType: triggerType,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> flushQueue() => (super.noSuchMethod(
        Invocation.method(
          #flushQueue,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> queueLength() => (super.noSuchMethod(
        Invocation.method(
          #queueLength,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
